name: 'trigger-release-please'
description: 'run Release Please externally'
author: Stainless

runs:
  using: 'node16'
  main: 'dist/index.js'

inputs:
  repo:
    description: 'The owner/name of the repo to run Release Pleas on. Example: lithic-com/lithic-python'
    required: true
  stainless-api-key:
    description: 'The API key provided to you by Stainless'
    required: true
  branch-with-changes:
    description: 'Name of the branch that contains changes for the release.'
    required: false